
# Server Configuration
server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always


# Spring Configuration
spring:
  #to enable colors when you run your app outside intellij
  output:
    ansi:
      enabled: always

  # Database Configuration
  datasource:
    url: jdbc:mysql://localhost:3307/taskflow_v1?createDatabaseIfNotExist=true
    username: root
    password:
  jpa:
    open-in-view: true
    show-sql: true
    hibernate:
      ddl-auto: create
    generate-ddl: false

  liquibase:
    enabled: false
  main:
    lazy-initialization: true

logging:
  file:
    name: taskFlow-api.log
  level:
    root: info
jwt:
  secret: Mati
  expiration: 3600
